server:
  port: 8080
spring:
  profiles: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: soft-certificate
        uri: lb://soft-certificate # lb代表从注册中心获取服务
        predicates:
          - Path=/soft-certificate/**
        filters:
          - RewritePath=/soft-certificate/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.ustb: debug