server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles: dev
  application:
    name: soft-certificate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://123.56.246.148:3306/softverify?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
    tomcat:
      max-idle: 8
      min-idle: 8
      initial-size: 10
  cache:
    ehcache:
      config: classpath:/ehcache.xml
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: 123.56.246.148
    port: 5672
    virtual-host: softVerify
    username: guest
    password: guest
    my-queue-name: sign-queue
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 512MB #设置总上传文件的大小
      max-file-size: 512MB #设置单个文件最大长度

#mybatis:
#  type-aliases-package: com.ustb.softverify.entity
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:com/ustb/softverify/mapper/xml/*.xml # xml所在路径
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册

#mybaits-plus
mybatis-plus:
  mapper-locations: classpath*:com/ustb/softverify/mapper/xml/*.xml
  map-underscore-to-camel-case: true
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ustb.softverify.entity
  global-config:
    #逻辑删除配置（下面3个配置）
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 1
      id-type: auto
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

jwt:
  config:
    key: itcast
    ttl: 604800
#文件上传配置
fileupload:
  config:
    # 文件上传目录
    uploadFolder: /Users/yorick/Downloads/uploadfile/
    # uploadFolder: c://webupload/
    #静态资源对外暴露的访问路径(访问图片的路径)
    staticAccessPath: storage/**
    # 设备截图文件保存路径(文件存在具体的文件夹的路径)
    localPath: fileData/
    #用户头像存放
    userHeaderPicPath: user/
    #档案文件存放
    archivesFilePath: webuploadfile/
    #访问域名和端口
    domain: http://localhost:${server.port}${server.servlet.context-path}

chainobj.address: 1MwnMpYGXy5TKJHMqiDy6MXorkQ5Nh6UoWCFEs
hostname: 123.56.246.148
name: root
password: chainNode202