server:
  port: 9004
spring:
  profiles: prod
  application:
    name: soft-certificate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.179.89:3306/softverify_join?characterEncoding=utf8
    username: root
    password: kingsoft
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 512MB #设置总上传文件的大小
      max-file-size: 512MB #设置单个文件最大长度

mybatis:
  type-aliases-package: com.ustb.softverify.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/ustb/softverify/mapper/xml/*.xml # xml所在路径
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://192.168.179.91:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册


#chainobj.address: 1Wkg9jF48VeM16rUE9MSTu4dfyvJv4dAb5X1v
chainobj.address: 1MwnMpYGXy5TKJHMqiDy6MXorkQ5Nh6UoWCFEs
hostname: 123.56.246.148
name: root
password: chainNode202
